version: "3.9"
services:
  db:
    ports:
      - "5433:5432"
    container_name: postgresql_container
    image: postgres:15
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: unless-stopped
  backend:
    build: .
    container_name: restaurant_app
    ports:
      - "5050:5050"
    environment:
      POSTGRES_DB: jdbc:postgresql://db:5432/test
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    depends_on:
      - db
    restart: unless-stopped