spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    secret_key: java8IsTheBest

server:
  port: 8080
  error:
    include-message: always
